/**
 * Jeeves
 * This is the api for the Jeeves web-service
 *
 * The version of the OpenAPI document: v1
 * Contact: stovgsb06@mail.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { User } from '../model/user';
import { UserAuth } from '../model/userAuth';
import { UserState } from '../model/userState';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * Logs user into the system
     * 
     * @param userAuth The user object for login
     */
    loginUser(userAuth?: UserAuth, extraHttpRequestParams?: any): Observable<UserState>;

    /**
     * Logs out currently logged in user session
     * 
     */
    logoutUser(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Register a new user
     * 
     * @param user 
     */
    register(user: User, extraHttpRequestParams?: any): Observable<UserState>;

}
