/**
 * Jeeves
 * This is the api for the Jeeves web-service
 *
 * The version of the OpenAPI document: v1
 * Contact: stovgsb06@mail.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Coctail } from '../model/coctail';


import { Configuration }                                     from '../configuration';



export interface CoctailServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * Creates a coctails
     * 
     * @param coctail 
     */
    createCoctails(coctail: Coctail, extraHttpRequestParams?: any): Observable<Coctail>;

    /**
     * Retrieves existent coctails
     * 
     */
    getCoctails(extraHttpRequestParams?: any): Observable<Array<Coctail>>;

}
