/**
 * Jeeves
 * This is the api for the Jeeves web-service
 *
 * The version of the OpenAPI document: v1
 * Contact: stovgsb06@mail.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { GroupedIngredients } from '../model/groupedIngredients';
import { Ingredient } from '../model/ingredient';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import {
    IngredientServiceInterface
} from './ingredient.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class IngredientService implements IngredientServiceInterface {

    protected basePath = 'http://localhost:8888/service/v2';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * Get ingredient by id
     * @param ingredientId Ingredient id to retrieve
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getIngredientById(ingredientId: number, observe?: 'body', reportProgress?: boolean): Observable<Ingredient>;
    public getIngredientById(ingredientId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Ingredient>>;
    public getIngredientById(ingredientId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Ingredient>>;
    public getIngredientById(ingredientId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (ingredientId === null || ingredientId === undefined) {
            throw new Error('Required parameter ingredientId was null or undefined when calling getIngredientById.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<Ingredient>(`${this.configuration.basePath}/ingredients/${encodeURIComponent(String(ingredientId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieves existent ingredients
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getIngredients(observe?: 'body', reportProgress?: boolean): Observable<Array<Ingredient>>;
    public getIngredients(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Ingredient>>>;
    public getIngredients(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Ingredient>>>;
    public getIngredients(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<Array<Ingredient>>(`${this.configuration.basePath}/ingredients`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieves existent ingredients
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getIngredientsInGroups(observe?: 'body', reportProgress?: boolean): Observable<Array<GroupedIngredients>>;
    public getIngredientsInGroups(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<GroupedIngredients>>>;
    public getIngredientsInGroups(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<GroupedIngredients>>>;
    public getIngredientsInGroups(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<Array<GroupedIngredients>>(`${this.configuration.basePath}/ingredients/inGroups`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
