/**
 * Jeeves
 * This is the api for the Jeeves web-service
 *
 * The version of the OpenAPI document: v1
 * Contact: stovgsb06@mail.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Ingredient } from '../model/ingredient';


import { Configuration }                                     from '../configuration';



export interface IngredientServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * Retrieves existent ingredients
     * 
     */
    getIngredients(extraHttpRequestParams?: any): Observable<Array<Ingredient>>;

}
