/**
 * Jeeves
 * This is the api for the Jeeves web-service
 *
 * The version of the OpenAPI document: v1
 * Contact: stovgsb06@mail.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Coctail } from './coctail';
import { Ingredient } from './ingredient';


export interface CoctailIngredient { 
    id?: number;
    coctail?: Coctail;
    ingredient?: Ingredient;
    volume?: number;
    unit?: string;
}


